name: nightly-windows-2022
env:
  name: staging_environment
  NODE_AUTH_TOKEN: ${{ secrets.PAT }}
  GITHUB_PAT: ${{ secrets.PAT }}
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  PHONE_NUMBER_ACCOUNT: ${{ secrets.PHONE_NUMBER_ACCOUNT }}
  PHONE_NUMBER_TOKEN: ${{ secrets.PHONE_NUMBER_TOKEN }}
  TEST1_EMAIL: ${{ secrets.TEST1_EMAIL }}
  TEST2_EMAIL: ${{ secrets.TEST2_EMAIL }}
  TEST3_EMAIL: ${{ secrets.TEST3_EMAIL }}
  TEST1_PHONE_NUMBER: ${{ secrets.TEST1_PHONE_NUMBER }}
  TEST2_PHONE_NUMBER: ${{ secrets.TEST2_PHONE_NUMBER }}
  TEST3_PHONE_NUMBER: ${{ secrets.TEST3_PHONE_NUMBER }}
  TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
  TEST_RESET_PASSWORD: ${{ secrets.TEST_RESET_PASSWORD }}

concurrency: staging_environment

on:
  push:
    paths:
      - "**/nightly-windows-2022.yml"
#
jobs:
  test-1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        node-version: [14]
    steps:
      - name: Get short SHA ðŸ”‘
        id: slug
        run: |
          echo "::set-output name=sha7::${GITHUB_SHA::7}"
        shell: bash

      - name: Checkout ${{ steps.slug.outputs.sha7 }} â¬‡ï¸   
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"
          scope: "@zeeis"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}

      - name: Install dependencies ðŸ‘¨ðŸ»â€ðŸ’»
        run: yarn install
      
      - name: Get last commit date
        id: vars
        run: |
          echo "::set-output name=date::$(git log -1 --date=format:'%Y%m%d' --format='%cd')"
          echo "event.tag:${{ github.event.release.tag_name }}"
          echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"
        shell: bash

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Checkout vars-date ${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.tag }} â¬‡ï¸
        run: |
          echo "${{ steps.vars.outputs.date }}"
          echo "tag1:${{ steps.vars.outputs.tag }}"
          echo "tag2:${{ steps.previoustag.outputs.tag }}"

      - name: Install winappdriver.msi
        run: | 
          Invoke-WebRequest "https://github.com/microsoft/WinAppDriver/releases/download/v1.2.1/WindowsApplicationDriver_1.2.1.msi" -OutFIle "C:\WindowsApplicationDriver_1.2.1.msi"
          Start-Process msiexec -ArgumentList "/quiet","/x","{087BBF93-D9E3-4D27-BDBE-9C702E0066FC}" -Verb runAs -Wait
          Start-Process msiexec -ArgumentList "/quiet","/i","C:\WindowsApplicationDriver_1.2.1.msi" -Verb runAs -Wait
          Start-Sleep -s 5
        shell: powershell

      - name: Install Alphabiz
        run: |
          curl -L https://github.com/tanshuai/alphabiz/releases/download/nightly-20220117-b5d39f6/alphabiz-windows-nightly-20220117-b5d39f6.7z > alphabiz.7z
          7z x alphabiz.7z
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
          GITHUB_PAT: ${{ secrets.PAT }}

      - name: Run appium
        run: |
          Start-Process PowerShell -ArgumentList "yarn appium --log ./test/output/release/appium.log"
          Start-Sleep -s 10
          
      - name: Run release test ðŸ§ª
        run: yarn run jest
      
      - name: Upload Test Results ðŸ—ƒ
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "output"
          path: output/**