name: CI/CT for each push
# env:
#   name: staging_environment

# concurrency: staging_environment

on:
  schedule:
    - cron: "00 12 * * *"
  push:
    paths:
      - "**.js"
      - "**/push.yml"
      - "build/**"
    branches: [main]
  pull_request:
    branches: [main]
#
jobs:
  test-1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, macos-latest]
        os: [ubuntu-latest, windows-2022, macos-latest]
        node-version: [14]
    environment:
      name: CICD
    env:
      NODE_AUTH_TOKEN: ${{ secrets.PAT }}
      GITHUB_PAT: ${{ secrets.PAT }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      PHONE_NUMBER_ACCOUNT: ${{ secrets.PHONE_NUMBER_ACCOUNT }}
      PHONE_NUMBER_TOKEN: ${{ secrets.PHONE_NUMBER_TOKEN }}
      TEST1_EMAIL: ${{ secrets.TEST1_EMAIL }}
      TEST2_EMAIL: ${{ secrets.TEST2_EMAIL }}
      TEST3_EMAIL: ${{ secrets.TEST3_EMAIL }}
      TEST1_PHONE_NUMBER: ${{ secrets.TEST1_PHONE_NUMBER }}
      TEST2_PHONE_NUMBER: ${{ secrets.TEST2_PHONE_NUMBER }}
      TEST3_PHONE_NUMBER: ${{ secrets.TEST3_PHONE_NUMBER }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_RESET_PASSWORD: ${{ secrets.TEST_RESET_PASSWORD }}
    steps:
      - name: Get short SHA ğŸ”‘
        id: slug
        run: |
          echo "::set-output name=sha7::${GITHUB_SHA::7}"
        shell: bash

      - name: Checkout ${{ steps.slug.outputs.sha7 }} â¬‡ï¸
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"
          scope: "@zeeis"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}

      - name: Get last commit date
        id: vars
        run: |
          git fetch --prune --unshallow
          echo "::set-output name=commit::$(git log -1 --pretty=%B --author="AlphabizTeam")"
          echo "::set-output name=commit-version::$(git log -1 --pretty=%B --author="AlphabizTeam" | perl -wnE'say for /(?<=v)\d+\.\d+\.\d+/g')"
          echo "::set-output name=commit-message::$(git log -1 --pretty=%B --author="AlphabizTeam" | perl -wnE'say for /\d{8,12}-\w+/g')"
          echo "::set-output name=date::$(git log -1 --date=format:'%Y%m%d' --format='%cd')"
          echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"
          echo "::set-output name=current-hour::$(date +'%H')"
          echo "::set-output name=release-date::$(git log -1 --date=format:'%Y-%m-%d' --format='%cd')"
        shell: bash

      # è·å–æ‰€ä»¥ä»Šå¤© ä½œè€…ä¸ºAlphabizTeamçš„commit message,æ­£åˆ™:ä¸åŒ¹é…'[-]ç¬¦å·'å‰é¢çš„ä»»æ„å­—ç¬¦ã€ä¸åŒ¹é…ç©ºè¡Œ
      - name: Get today all commit message
        run: |
          export DESCRIBE=$(git log --reverse --after="${{ steps.vars.outputs.release-date }} 00:00" --before="${{ steps.vars.outputs.release-date }} 23:59" --author="AlphabizTeam" --pretty='format:%B' | perl -wnE'say for /(?!.*-)(?!\s).*\w+$/gm')
          echo "$DESCRIBE"
          echo "DESCRIBE<<EOF" >> $GITHUB_ENV
          echo "$DESCRIBE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        shell: bash

      - name: Checkout vars-date ${{ steps.vars.outputs.date }} â¬‡ï¸
        run: |
          echo "commit: ${{ steps.vars.outputs.commit }}"
          echo "commit-version: ${{ steps.vars.outputs.commit-version }}"
          echo "commit-message: ${{ steps.vars.outputs.commit-message }}"
          echo "${{ steps.vars.outputs.date }}"
          echo "${{ steps.vars.outputs.tag }}"
          echo "current-hour: ${{ steps.vars.outputs.current-hour }}"
          echo "----------------------"
          echo "${{ env.DESCRIBE }}"

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
          GITHUB_PAT: ${{ secrets.PAT }}

      - name: Install UnPackaged ğŸ‘¨ğŸ»â€ğŸ’»
        run: |
          cd build/electron/UnPackaged
          yarn
        shell: bash

      - name: Patch unpackaged node_modules
        run: yarn patch-unpackaged

      - name: E2E Test for Electron ğŸ§ª
        run: yarn test:e2e:electron

      - name: E2E Test ğŸ§ª
        run: yarn test:e2e:ci

      - name: Upload Test Results ğŸ—ƒ
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "output1"
          path: test/output/**

      #åé¢çš„stepæ™šä¸Šè¿è¡Œ

      - name: Run electron-packager
        if: contains(steps.vars.outputs.current-hour, '12')
        run: yarn packager

      - name: Package for ${{ matrix.os }}-nightly-${{ steps.vars.outputs.commit-message }} Release ğŸ—œï¸
        if: contains(steps.vars.outputs.current-hour, '12')
        run: 7z a -t7z -mx=9 alphabiz-${{ matrix.os }}-${{ steps.vars.outputs.commit-version }}-nightly-${{ steps.vars.outputs.commit-message }}.7z ./build/electron -xr!UnPackaged

      # - name: Pack app ğŸ“¦
      #   run: |
      #     export PATH=$PATH:/c/Program\ Files\ \(x86\)/WiX\ Toolset\ v3.11/bin
      #     yarn make
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.PAT }}
      #     GITHUB_PAT: ${{ secrets.PAT }}
      #   shell: bash

      - name: Release ${{ matrix.os }}-nightly-${{ steps.vars.outputs.commit-message }}.7z to GitHub ğŸ“°
        if: contains(steps.vars.outputs.current-hour, '12')
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          name: test-${{ steps.vars.outputs.commit-version }}-alphabiz-nightly-${{ steps.vars.outputs.commit-message }}
          tag_name: test-${{ steps.vars.outputs.commit-version }}-nightly-${{ steps.vars.outputs.commit-date }}
          body: ${{ env.DESCRIBE }}
          files: |
            alphabiz-${{ matrix.os }}-${{ steps.vars.outputs.commit-version }}-nightly-${{ steps.vars.outputs.commit-message }}.7z
